# Generated by Django 5.2.6 on 2025-09-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='negative_mark',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Mark to be deducted for each wrong answer (e.g., 0.25).', max_digits=4),
        ),
    ]
